"use server";

import { revalidatePath } from "next/cache";

import {
  findOverlap,
  toHHMM,
  toPgTime,
  validateSlot,
  type AvailabilitySlot,
} from "@/lib/availability";
import { serverDb } from "@/lib/data/db";

export type AvailabilityResult =
  | { status: "anonymous" }
  | { status: "not-teacher" }
  | { status: "ok"; slots: AvailabilitySlot[]; timezone: string }
  | { status: "error"; message: string };

/**
 * Recurring weekly availability for the signed-in teacher.
 *
 * The rows are `public.teacher_availability`, which replaced the free-text
 * `availabilityHours` label ("Lun-Ven 14-20h") that nothing could be booked
 * against. The returned shape is `WeekSlot`, so the existing week grid renders
 * it with no adapter.
 */
export async function loadMyAvailabilityAction(): Promise<AvailabilityResult> {
  const db = await serverDb();
  const {
    data: { user },
  } = await db.auth.getUser();
  if (!user) return { status: "anonymous" };

  const { data: teacher } = await db
    .from("teacher_profiles")
    .select("user_id, timezone")
    .eq("user_id", user.id)
    .maybeSingle();
  if (!teacher) return { status: "not-teacher" };

  const { data, error } = await db
    .from("teacher_availability")
    .select("id, weekday, starts_at, ends_at")
    .eq("teacher_id", user.id)
    .order("weekday")
    .order("starts_at");

  if (error) {
    return { status: "error", message: "Disponibilités illisibles." };
  }

  return {
    status: "ok",
    timezone: teacher.timezone,
    slots: (data ?? []).map((row) => ({
      id: row.id,
      day: row.weekday,
      start: toHHMM(row.starts_at),
      end: toHHMM(row.ends_at),
    })),
  };
}

/**
 * Replaces the whole week in one go.
 *
 * Replace rather than diff: the grid hands back the full set after every edit,
 * a week is a handful of rows, and a replace cannot drift out of sync with
 * what the teacher is looking at. Slot ids are regenerated by the database, so
 * the caller adopts the returned set.
 */
export async function saveMyAvailabilityAction(
  slots: AvailabilitySlot[],
): Promise<AvailabilityResult> {
  const db = await serverDb();
  const {
    data: { user },
  } = await db.auth.getUser();
  if (!user) return { status: "anonymous" };

  const { data: teacher } = await db
    .from("teacher_profiles")
    .select("user_id, timezone")
    .eq("user_id", user.id)
    .maybeSingle();
  if (!teacher) return { status: "not-teacher" };

  if (slots.length > 200) {
    return { status: "error", message: "Trop de créneaux (200 maximum)." };
  }

  // Same rules as the table's CHECK constraints and its exclusion constraint,
  // applied first so the teacher reads French instead of a Postgres error.
  for (const slot of slots) {
    const problem = validateSlot(slot);
    if (problem) return { status: "error", message: problem };
  }
  const overlap = findOverlap(slots);
  if (overlap) return { status: "error", message: overlap };

  const { error: deleteError } = await db
    .from("teacher_availability")
    .delete()
    .eq("teacher_id", user.id);
  if (deleteError) {
    return { status: "error", message: "Enregistrement impossible." };
  }

  if (slots.length > 0) {
    const { error: insertError } = await db
      .from("teacher_availability")
      .insert(
        slots.map((slot) => ({
          teacher_id: user.id,
          weekday: slot.day,
          starts_at: toPgTime(slot.start),
          ends_at: toPgTime(slot.end),
        })),
      );
    if (insertError) {
      // 23P01 is teacher_availability_no_overlap, the last line of defence if
      // the client-side check was bypassed by a direct POST.
      if (insertError.code === "23P01") {
        return { status: "error", message: "Deux créneaux se chevauchent." };
      }
      return { status: "error", message: "Enregistrement impossible." };
    }
  }

  revalidatePath("/teacher/sessions");

  const { data } = await db
    .from("teacher_availability")
    .select("id, weekday, starts_at, ends_at")
    .eq("teacher_id", user.id)
    .order("weekday")
    .order("starts_at");

  return {
    status: "ok",
    timezone: teacher.timezone,
    slots: (data ?? []).map((row) => ({
      id: row.id,
      day: row.weekday,
      start: toHHMM(row.starts_at),
      end: toHHMM(row.ends_at),
    })),
  };
}
